### ISSUE TITLE
App icon changes when you open a new window

### ISSUE THREAD

**Issue by ximocat** [cavearr/icestudio-nightly#1]
En windows 7 64 bits, me sucede que cuando abro por primera vez Icestudio el icono de la aplicación que aparece arriba a la izquierda es el de Icestucio, pero al pulsar en Archivo->Nuevo se abre una nueva ventana pero con un icono diferente. Adjunto pantallazo.

Muchas gracias :)
![iconos_icestudio](https://user-images.githubusercontent.com/25247003/56803718-a7362b80-6823-11e9-9e0c-fb68aded8970.jpg)

**Comment by cavearr** [comment]
Hola Ximo, muchas gracias! lo revisaré, en principio no te preocupes eso es porque icestudio está construido sobre nwjs, un framework parecido a electrón y esto debe ser un bug del propio nwjs que es el motor de la aplicación nativa. 

En cuanto al funcionamiento no te va a afectar para nada, pero lo voy a revisar para intentar dejarlo perfecto. 

Muchísimas gracias por el test! 


De: "Ximo Catala" <notifications@github.com> 
Para: "cavearr/icestudio-nightly" <icestudio-nightly@noreply.github.com> 
CC: "Subscribed" <subscribed@noreply.github.com> 
Enviados: Viernes, 26 de Abril 2019 13:03:48 
Asunto: [cavearr/icestudio-nightly] App icon changes when you open a new window (#1) 



En windows 7 64 bits, me sucede que cuando abro por primera vez Icestudio el icono de la aplicación que aparece arriba a la izquierda es el de Icestucio, pero al pulsar en Archiv a Nuevo se abre una nueva ventana pero con un icono diferente. Adjunto pantallazo. 

Muchas gracias a

**Comment by cavearr** [comment]
En principio resuelto en la nueva nightly, si vuelve a aparecer reabrir issue.
