### ISSUE TITLE
Copy/Paste

### ISSUE THREAD

**Issue by Democrito** [cavearr/icestudio-nightly#10]
Hola Carlos,

Tengo un problema en Windows con la última versión a día de hoy (0.5.1n201009). No consigo pegar los elementos que copié. Sé que hace el copy porque si me voy a un editor de texto y le doy a pegar, suelta "el código" de lo que se supone que copié como elementos. pero no salen esos elementos (no hace nada al hacer contro V).

No sé si es un problema de Icestudio, o Windows crea algún problema en ello.

Saludos!

**Comment by Democrito** [comment]
Por si me he explicado mal, quise decir que en Icestudio no hace nada al hacer control V, no salen los elementos que copié.

**Comment by cavearr** [comment]
Puedes probar a hacerlo con copy y paste pero desde el menu edit?

**Comment by Democrito** [comment]
Perdona Carlos, acabo de llegar de currar y pese a que puedo ver ciertas cosas no puedo contestar porque el móvil lo tengo desvinculado de mis cuentas oficiales.

Sí, ya lo prové, tampoco funciona, ni el clon. He probado y combinado todas las formas posible.

Estoy a tus órdenes de pruebas y lo que necesites. Pero sería bueno saber si hay más gente que le pasa o son casos aislados (recuerdo a José Picó que también le sucedía lo mismo con otras versiones, pero a mí no me sucedía).

Saludos!

**Comment by cavearr** [comment]
Gracias Demócrito! tus pruebas y feedback siempre es fantástico.

Voy a instalarlo de cero en un windows limpio y a ver si veo que es, estoy cerrando otros puntos y sacaremos una nightly en breve así que si solucionamos esto mejor que mejor.

¿qué versión de windows usas?, esto es muy importante para poder acotar y si hace falta me instalo la misma versión.

Gracias!

**Comment by Democrito** [comment]
Windows Home
![version windows](https://user-images.githubusercontent.com/5473407/98993091-4d44a600-252e-11eb-9e03-1cfc482f65a1.PNG)

Adjunto datos que da el SO.

**Comment by Democrito** [comment]
Voy a probar en otro ordenador... No se me ocurrió antes.

**Comment by Democrito** [comment]
En el otro portátil todo va bien. Jolines, qué raro es todo. También es Windows 10 home de 64 bits. La única diferencia es que el que no hace copy/paste es Intel y el otro es AMD.

En el otro ordenador desinstalé la versión antigua de Icestudio, borré cualquier carpeta llamada "Icestudio", hice una limpieza de registro y luego instalé la nueva versión de Icestudio. Hice pruebas tal cual, todo bien. Luego añadí la última versión de la colección Jedi de Obijuan, y todo bien.

No encuentro lógica a lo que sucede en este otro portátil.

Saludos.

**Comment by Democrito** [comment]
Este finde voy a trabajar en el otro ordenador, y comprobaré si vuelve a sucede o no. Y haré muchos copys/pastes por necesidad.

Cualquier cosa que vea te comento y estaré atento a ver si hay algo en que comience a darse, si fuese el caso.

**Comment by cavearr** [comment]
Gracias!!!

Yo probaré de todos modos.

**Comment by Democrito** [comment]
He hecho una re-instalación limpia de Windows 10 y de momento todo va bien. Debí de tocar la configuración de Windows o algo hice para que luego diese ese fallo.

A los "manazas" nos suele sucede cosas extrañas...

**Comment by cavearr** [comment]
Perfecto! cierro esta issue entonces de momento.

gracias por las pruebas!

**Comment by Obijuan** [comment]
Es cierto que hay un bug extraño en el copy&paste en windows, pero todavía no sabemos reproducirlo. Ocurre de vez en cuando a diferentes usuarios. Le pasó a Jose Picó en dos ordenadores y ahora a demócrito. El problema está ahí, lo que ocurre que al no poder reproducirlo es muy difícil de encontrar. Aunque se cierre este issue, hay que estar atentos
