### ISSUE TITLE
Windows 64 - Icestudio Nightly 5.1

### ISSUE THREAD

**Issue by Democrito** [cavearr/icestudio-nightly#2]
Hola Carlos,

Manejo Windows 64 bits. Me bajé la versión que está en: https://icestudio.io/ la nightly, y no funciona, se queda en una ventana en blanco, eso es todo, no aparece nada.

Ahora voy a probar la versión que tienes en github, como .zip y te cuento.

Saludos!

**Comment by Democrito** [comment]
Tampoco funciona ejecutando el zip. Previamente desinstalé todo e incluso limpié el registro con CCleaner. Adjunto imagen de mensaje de error.

Saludos!
![mensaje](https://user-images.githubusercontent.com/5473407/67904165-e09e7980-fb6d-11e9-972a-511bd3c2c80e.PNG)

**Comment by cavearr** [comment]
Hola Demócrito, voy a echarle un vistazo ahora mismo en el windows en el que he testeado si ha funcionado pero efectivamente si has detectado esto es porque no funciona en algunos entornos.

Voy a ponerme a ello.

**Comment by Democrito** [comment]
Adjunto imagen que me sale al ejecutar una vez instalado.
![ventanaBlanca](https://user-images.githubusercontent.com/5473407/67932028-6e588400-fbc3-11e9-8940-4434fa3d1a73.PNG)

**Comment by cavearr** [comment]
En principio ya está solucionado, cuando puedas descarga el nuevo binario y me confirmas.

Gracias!

**Comment by Democrito** [comment]
Además de Windows 64 te confirmo por aquí que en un Windows 7 a 32 bits funciona igual de bien. Lo probé en un ordenador que está en las últimas y no tuve ningún problema.

Millón de gracias siempre a ti!
