### ISSUE TITLE
Al darle "abrir" o "nuevo" dentro de Icestudio y al hacer doble clic a un segundo "ICE" en Windows.

### ISSUE THREAD

**Issue by Democrito** [cavearr/icestudio-nightly#3]
Hola Carlos,

**1.)** Dentro de Icestudio 5.1 al darle a "abrir" para cargar otro archivo diferente al que se está trabajando (tener dos circuitos diferentes activos) en apariencia lo carga, pero sucede que vuelve a cargar el mismo que está en la ventana anterior (desde la que se abrió otro circuito). Si se insiste en volver a cargarlo entonces lo hace bien, pero hay que hacerlo dos veces.

Si se mira con ojo de águila se nota el cambio, cómo pasa del circuito que quieres abrir, al mismo que ya estabas trabajando, lo hace muy rápido.

Y lo dicho, al volver a intentarlo entonces lo hace bien y tienes el circuito que estabas trabajando y el nuevo que acabas de abrir.

**2.)** Otro problema es que no permite abrir dos o más proyectos a la vez cuando hago doble clic con el ratón al icono (ICE de otros proyectos) que quiero abrir, sólo permite uno, no permite dos o más ICES abiertos. Esto en la 5.0 lo permitía.

**3.)** Al darle a "Nuevo" sucede lo mismo que en el punto 1.) que se vuelve a abrir el ICE con el que se está trabajando, en vez de abrir una ventana nueva vacía.

Si no me he explicado bien me lo dices y miraré la forma de explicarlo mejor.
Igual esto sólo sucede en Windows.

Muchas gracias por todo!

**Comment by cavearr** [comment]
Hola Demócrito! efectivamente es un problema en windows, pero me pongo a ello, la 0.5.1 tiene que quedar perfecta. 

Te voy informando! 


De: "Democrito" <notifications@github.com> 
Para: "cavearr" <icestudio-nightly@noreply.github.com> 
CC: "Subscribed" <subscribed@noreply.github.com> 
Enviados: Martes, 5 de Noviembre 2019 23:18:44 
Asunto: [cavearr/icestudio-nightly] Al darle "abrir" o "nuevo" dentro de Icestudio y al hacer doble clic a un segundo "ICE" en Windows. (#3) 



Hola Carlos, 

1.) Dentro de Icestudio 5.1 al darle a "abrir" para cargar otro archivo diferente al que se está trabajando (tener dos circuitos diferentes activos) en apariencia lo carga, pero sucede que vuelve a cargar el mismo que está en la ventana anterior (desde la que se abrió otro circuito). Si se insiste en volver a cargarlo entonces lo hace bien, pero hay que hacerlo dos veces. 

Si se mira con ojo de águila se nota el cambio, cómo pasa del circuito que quieres abrir, al mismo que ya estabas trabajando, lo hace muy rápido. 

Y lo dicho, al volver a intentarlo entonces lo hace bien y tienes el circuito que estabas trabajando y el nuevo que acabas de abrir. 

2.) Otro problema es que no permite abrir dos o más proyectos a la vez cuando hago doble clic con el ratón al icono (ICE de otros proyectos) que quiero abrir, sólo permite uno, no permite dos o más ICES abiertos. Esto en la 5.0 lo permitía. 

3.) Al darle a "Nuevo" sucede lo mismo que en el punto 1.) que se vuelve a abrir el ICE con el que se está trabajando, en vez de abrir una ventana nueva vacía. 

Si no me he explicado bien me lo dices y miraré la forma de explicarlo mejor. 
Igual esto sólo sucede en Windows. 

Muchas gracias por todo!

**Comment by Obijuan** [comment]
Lo he conseguido reproducir también desde Linux. Para ello arranco icestudio desde el navegador de archivos haciendo doble click en un fichero .ice de ejemplo:

* se abre correctamente
* Al darle a Archivo/Nuevo, en vez de crear un proyecto en blanco se abre el anterior
* Si cuando hay uno abierto, desde el Navegador de ficheros se intenta abrir otro, no hace nada

![Peek 2019-11-06 09-29](https://user-images.githubusercontent.com/1286062/68281709-8b380000-0078-11ea-92e0-fc45dbb8863b.gif)

**Comment by cavearr** [comment]
Demócrito, podrías confirmarme si desde tu windows, si en vez de abrir con doble click, lo abres desde el menú Archivo todo funciona bien?

Es decir que el error se produce sólo al abrir proyectos con doble click.

**Comment by Obijuan** [comment]
En Linux te confirmo que al abrir desde el menú Archivo/Open se abren correctamete y se pueden tener varios. Sólo he detectado el problema cuando se abren con el doble click en el navegador de archivos

**Comment by cavearr** [comment]
Gracias Juan! en cuanto confirme Demócrito que en windows pasa igual, investigaré como solucionarlo ya que es un problema del nuevo motor nwjs que gestiona de diferente forma los hilos.

**Comment by Democrito** [comment]
Es extraño, hoy parece que tenga otro comportamiento. Comento exactamente lo que veo:

**1.)** Tengo un solo ICE abierto, y sin modificar nada dentro de él, ahora le doy a abrir dentro del menú de Icestudio para abrir otro ICE. Me lo abre, pero se cierra el anterior y me queda el último que abrí.

**2.)** Cierro todo. Comienzo de cero. Abro un ICE y le modifico algo (por ejemplo muevo un bloque), luego le doy a "abrir" (u "open") dentro del menú de Icestudio y me lo abre bien.

**Comment by Democrito** [comment]
Acabo de descargar un programa que pasa de pantalla a gif, como hace Juan. Para el primer caso, abro un ICE, una vez abierto le doy a abrir otro (sin modificar nada), entonces desaparece el primer ICE y sólo queda el segundo ICE abierto. Aquí hubiera esperado tener dos ICES abiertos.

![abrir_otro_ice_sin_cambios](https://user-images.githubusercontent.com/5473407/68295913-b845dc00-0093-11ea-84cd-8f1f7977f2af.gif)

**Comment by Obijuan** [comment]
si, ese comportamiento está implementado así a posta (no es un bug). Lo implementó Jesús así. Podemos establecer que el comportamiento sea otro, si es más cómodo, pero no está relacionado con este bug. Yo también creo que es más cómodo que cada vez que le des a abrir, aparezca en una ventana nueva

**Comment by Democrito** [comment]
Ahora pongo el segundo caso. Abro un ICE y a ese ICE le modifico algo. Luego le doy a "abrir" otro ICE dentro de Icestudio. Entonces trata de abrirlo, pero vuelve a cargar el que ya estaba abierto (no el que le pedí). Cierro ese segundo ICE. Vuelvo a darle a abrir para cargar el ICE que quería cargar (el mismo que le pedí anteriormente). Ahora lo carga bien.


![abrir_otro_ice_con_cambios](https://user-images.githubusercontent.com/5473407/68296798-ba109f00-0095-11ea-9b2f-ee0055cabc9c.gif)

**Comment by Democrito** [comment]
Y por último el que haciendo doble clic para que se abra, sólo se abre uno. Primero lo hago con un ICE y luego repito lo mismo con otro ICE.

![Con_clic_solo_abre_uno](https://user-images.githubusercontent.com/5473407/68297373-0c9e8b00-0097-11ea-9a66-a8e223eefda1.gif)

**Comment by cavearr** [comment]
Fantásticas pruebas! como te ha comentado Juan, lo de que si no modifiques "te lo pise" está implementado así desde el inicio, ami tampoco me gusto, esto por votación popular si quereis lo cambiamos :)

El resto fantástico con esto podré reproducir vuestros pasos y buscar solución, el problema sé cual es, lo que no tengo aún claro es como solucionarlo, pero vamos a investigar.

**Comment by Democrito** [comment]
Mucha fuerza! (metáfora de star wars)

**Comment by cavearr** [comment]
Buenas! ya teneis los nuevos binarios subidos, os comento:

1) Aperturas de proyectos desde el icestudio abierto, debería funcionar correctamente aunque vereis que hay un parón  antes de cargar el proyecto indicado, esto ahora es inevitable por la arquitectura actual y veo complicado cambiarlo a corto plazo, así que habrá que acostumbrarse a esa "paroncillo".

2) Aperturas con doble click, sólo funcionará la primera, hay que hacer un cambio de arquitectura bastante importante para que funcionen aperturas seguidas con doble click. La arquitectura actual de nwjs no permite abrir varias instancias simultáneas y tenemos que implementar ese control en el inicio de icestudio, es un cambio importante que haremos en las siguientes nightlies. De momento  saber que el primer doble click debería funcionar bien pero a aprtir de ahí se deberían abrir los proyectos desde el menú.

Ya me confirmais si queda resuelto o si os sigue dando problemas.

**Comment by Obijuan** [comment]
Lo acabo de probar ahora.  Me sigue fallando el crear un proyecto nuevo tras haber abierto uno antes con doble click. Primero hago doble click, y se abre un proyecto. Eso está ok. Luego desde dentro de icestudio le doy a Archivo/Nuevo pero no me crea una ventana con un proyecto en blanco, sino que vuelve a abrir el original. Y tengo dos ventanas con el proyecto original

![Peek 2019-11-07 17-42](https://user-images.githubusercontent.com/1286062/68408753-32ef2400-0186-11ea-95d2-8561fa1ebad4.gif)

**Comment by Obijuan** [comment]
El resto me va bien. Puedo abrir abrir proyectos desde dentro sin problemas, en Linux

**Comment by cavearr** [comment]
se me había pasado mirar lo del NEW, ya estoy con ello!

**Comment by Democrito** [comment]
Todavía no he instalado la nuevo versión que mencionas, y ayer me di cuenta de una cosa que me sorprendió y que rara vez lo hace aunque lo provoque. Lo que voy a comentar es subjetivo, pero creo que teniendo abierto un ICE (se entiende que tengo abierto Icestudio), al tratar de abrir otro haciendo doble clic al icono se crea un archivo llamado "debug.log", pero esto lo hace muy, pero que muy rara vez, Sólo me ha pasado dos veces. Adjunto el fichero.
[debug.log](https://github.com/cavearr/icestudio-nightly/files/3821891/debug.log)

**Comment by cavearr** [comment]
Hola Juan, Demócrito os he dejado nuevo binario, creo que ya está solucionado tanto el abrir proyectos como el nuevo.

La primera apertura por click funcionará correctamente.

La segunda apertura por click fallará y tendrá un comportamiento errático a veces crujiendo y generando el debug.log.

El debug.log es una nueva característica del nuevo motor, cuando hay un fallo crítico lo genera para dar alguna pista.

LA apertura de ficheros por clicks a partir del primero lo tendré resuelto para la proxima nightly como os comento tengo que cambiar partes imporantes del core y va a ser delicado.

Espero vuestra confirmación de que salvo la apertura del segundo fichero por doble click, el resto funciona perfecto.

Gracias!

**Comment by Obijuan** [comment]
Te confirmo que en Linux funciona perfecto! :-)  ¡Gracias!

Con doble click abro un proyecto nuevo desde el navegador de archivos. Ahora le doy a Archivo/Nuevo y se me abre una ventana nueva con el proyecto en blanco

**Comment by Democrito** [comment]
Hey Carlos! Ahora sí! Me abre una ventana en blanco cuando le doy a "new" y abro (load) otros proyectos dentro de Icestudio.

Muchísimas gracias!

**Comment by Democrito** [comment]
Con abrir otros proyectos, me refería a que ahora sí puedo tener varios ICES abiertos sin problemas! Suelo trabajar así, copiando y pegado de varios proyectos al que esté trabajando en ese momento. Se agradece mucho por la comodidad que da.

**Comment by cavearr** [comment]
Perfecto democrito!!

Tu cualquier cosa que veas dale caña a las Issues que está genial todos estos fallos que detectáis.

----- Mensaje original -----
De: Democrito <notifications@github.com>
Para: cavearr/icestudio-nightly <icestudio-nightly@noreply.github.com>
CC: Carlos Venegas Arrabé <carlos@magnitude.es>, Comment <comment@noreply.github.com>
Enviado: Fri, 08 Nov 2019 21:41:49 +0100 (CET)
Asunto: Re: [cavearr/icestudio-nightly] Al darle "abrir" o "nuevo" dentro de Icestudio y al hacer doble clic a un segundo "ICE" en Windows. (#3)

Con abrir otros proyectos, me refería a que ahora sí puedo tener varios ICES abiertos sin problemas! Suelo trabajar así, copiando y pegado de varios proyectos al que esté trabajando en ese momento. Se agradece mucho por la comodidad que da.

**Comment by cavearr** [comment]
Cerrado en la nueva nightly, si aparece de nuevo volver a abrir.
