### ISSUE TITLE
No se actualiza bloque cuando se modifica fuera.

### ISSUE THREAD

**Issue by Democrito** [cavearr/icestudio-nightly#5]
Hola!
Se trata de que cuando se incluye un bloque, y aparte luego modificamos dicho bloque, al volverlo a incluir no se actualiza con las modificaciones hechas, sino que sigue el viejo bloque (sin estar actualizado).

En cambio, si modificamos el bloque dentro del mismo diseño, todo funciona perfecto. 

El problema surge cuando se modifica fuera, que al incluirlo no se actualiza, sigue el que estaba.

Un saludo!

PD: Si no me explico bien me lo comentas. Es un viejo bug y tiene una solución de "estar por casa", que es eliminar el bloque, guardar el circuito general, y al volver a abrir el circuito general, incluir el bloque actualizado, y volver a crear las conexiones; así sí lo pilla con las nuevas modificaciones.
Para mí este bug no es importante, porque hoy en día modifico directamente un bloque desde el circuito que tengo abierto.

**Comment by cavearr** [comment]
Hola Demócrito! si te he entendido bien, te refieres al siguiente escenario:

1) Tienes un bloque en un fichero A.ice
2) Importas como bloque ese fichero A.ice dentro de otro diseño B.ice
3) Si modificas el A.ice NO se modifica el bloque en B.ice

¿Es esto a lo que te refieres?

Si es este escenario, efectivamente esto aún no lo hace Icestudio. Cuando añades un bloque incluso de una colección, pasa a ser un elemento ya de ese diseño y no se vuelve a actualizar jamás. Por ejemplo si usas un bloque de una colección y dicho bloque se actualiza en el diseño donde lo hayas usado seguirá la versión vieja.

Esto sí que tengo en mente meterlo como una nueva feature más adelante.

Si no es esto a lo que te refieres, intenta explicar mejor el escenario.

**Comment by cavearr** [comment]
Demócrito, creo que acabo de reproducir lo que dices! eres una máquina! muchas gracias por testar y reportar!! voy a investigarlo y le damos solución.
